111111version: 0.2
phases:
  install:
    commands:
      - echo "install phase..."
      - apt-get update
      - apt-get install -y jq python-pip nodejs
      - pip install awscli
  build:
    commands:
      - echo "build phase..."
      - sh release.sh
